# Generated by Django 3.0 on 2019-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
