# Generated by Django 3.0 on 2019-12-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0002_shorturl_is_converted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='is_converted',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
