# Generated by Django 3.0 on 2019-12-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0003_auto_20191206_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
