# Generated by Django 3.0 on 2019-12-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='long_url',
            field=models.CharField(max_length=200),
        ),
    ]
