# Generated by Django 3.0 on 2019-12-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_auto_20191211_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortener',
            old_name='short_code',
            new_name='short',
        ),
    ]
