# Generated by Django 3.0 on 2019-12-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_auto_20191211_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
