# Generated by Django 3.0 on 2019-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
    ]
