# Generated by Django 3.0 on 2019-12-04 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complete_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Completed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Created'),
        ),
    ]
