# Generated by Django 3.0 on 2019-12-04 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryList', '0005_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
