# Generated by Django 3.0.1 on 2020-01-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_me_app', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
