# Generated by Django 3.0.1 on 2020-01-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_me_app', '0004_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
