# Generated by Django 3.0.1 on 2020-01-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_me_app', '0007_auto_20200128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
