# Generated by Django 3.0.2 on 2020-01-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='favorite',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(max_length=100, null='true'),
            preserve_default='true',
        ),
    ]
