# Generated by Django 3.0.2 on 2020-02-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200202_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
