# Generated by Django 3.0.2 on 2020-02-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200202_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(blank='true', null='true'),
        ),
    ]
