# Generated by Django 3.0.2 on 2020-02-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200202_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='locals_pics'),
        ),
    ]
