# Generated by Django 3.0.2 on 2020-02-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200203_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.CharField(max_length=200, null='true'),
        ),
    ]
