# Generated by Django 3.0.2 on 2020-02-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200203_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
    ]
