# Generated by Django 3.0 on 2019-12-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191211_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='my_image',
            field=models.ImageField(default='uploaded_files/avatar/null.jpg', upload_to='avatar/'),
        ),
    ]
