# Generated by Django 3.0 on 2019-12-04 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 12, 4, 20, 12, 5, 656210, tzinfo=utc))),
                ('completed_date', models.DateTimeField(default=datetime.datetime(2019, 12, 4, 20, 12, 5, 656246, tzinfo=utc))),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
