# Generated by Django 3.0 on 2019-12-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist_app', '0002_auto_20191204_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
