# Generated by Django 2.2.7 on 2020-01-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200124_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Api',
        ),
    ]
