# Generated by Django 3.0 on 2019-12-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlibapp', '0002_auto_20191206_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='madlibword',
            name='is_madlibword',
            field=models.BooleanField(default=True),
        ),
    ]
