# Generated by Django 3.0 on 2019-12-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madlibapp', '0003_madlibword_is_madlibword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madlibword',
            name='is_madlibword',
        ),
        migrations.RemoveField(
            model_name='madlibword',
            name='word_type',
        ),
    ]
