# Generated by Django 3.0 on 2019-12-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoosh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='ip_orig',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
