# Generated by Django 3.0 on 2019-12-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='date_created',
        ),
    ]
