# Generated by Django 3.0 on 2019-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_remove_groceryitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='date created'),
        ),
    ]
