# Generated by Django 3.0 on 2019-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0004_auto_20191206_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
