# Generated by Django 3.0 on 2020-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='clan_is_disbanded',
            field=models.BooleanField(null=True),
        ),
    ]
