# Generated by Django 3.0 on 2020-01-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_clan_clan_is_disbanded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='ship_id',
            new_name='ship_wgid',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_id',
            new_name='skill_wgid',
        ),
        migrations.RenameField(
            model_name='upgrade',
            old_name='upgrade_id',
            new_name='upgrade_wgid',
        ),
        migrations.AddField(
            model_name='ship',
            name='ship_upgrades',
            field=models.ManyToManyField(related_name='ship_upgrades', to='data.Upgrade'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_class',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_nation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_upgrade_slots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_picture_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_tier',
            field=models.IntegerField(null=True),
        ),
    ]
