# Generated by Django 3.0 on 2019-12-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_auto_20191203_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroseryItem',
            new_name='GroceryItem',
        ),
    ]
