# Generated by Django 3.0 on 2019-12-11 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Please add a headline.', max_length=40)),
                ('summary', models.CharField(default='Please add a summary.', max_length=250)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/profiles/')),
                ('location', models.CharField(default='Please add a location.', max_length=30)),
                ('first_name', models.CharField(default='Please add a first name.', max_length=12)),
                ('last_name', models.CharField(default='Please add a last name.', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
