# Generated by Django 3.0 on 2019-12-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191211_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='images/profiles/default-profile.png', upload_to='images/profiles/'),
        ),
    ]
