# Generated by Django 3.0 on 2019-12-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_users_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='users_followed',
            field=models.ManyToManyField(related_name='friends', to='users.Profile'),
        ),
    ]
