# Generated by Django 3.0 on 2019-12-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20191213_1546'),
        ('users', '0005_auto_20191213_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chirps_disliked',
            field=models.ManyToManyField(related_name='dislikes', to='posts.Chirp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chirps_liked',
            field=models.ManyToManyField(related_name='likes', to='posts.Chirp'),
        ),
    ]
