# Generated by Django 3.0 on 2019-12-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_chirp_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='text',
            field=models.TextField(),
        ),
    ]
