# Generated by Django 3.0 on 2019-12-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/chirps/'),
        ),
    ]
