# Generated by Django 3.0 on 2020-01-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_wgid', models.IntegerField()),
                ('battle_map', models.CharField(max_length=50)),
                ('battle_realm', models.CharField(max_length=10)),
                ('battle_arena_id', models.IntegerField()),
                ('battle_finished_at', models.DateTimeField()),
                ('battle_season_number', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClanInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claninstance_wgid', models.IntegerField()),
                ('claninstance_team_no', models.IntegerField()),
                ('claninstance_division', models.IntegerField()),
                ('claninstance_league', models.IntegerField()),
                ('claninstance_rating', models.IntegerField()),
                ('claninstance_rating_delta', models.IntegerField()),
                ('claninstance_result', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('claninstance_battle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan_battles.Battle')),
                ('claninstance_clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerinstance_wgid', models.IntegerField()),
                ('playerinstance_player_name', models.CharField(max_length=100)),
                ('playerinstance_survived', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('playerinstance_clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Clan')),
                ('playerinstance_claninstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clan_battles.ClanInstance')),
                ('playerinstance_ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Ship')),
            ],
        ),
    ]
