# Generated by Django 3.0 on 2020-01-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('clan_battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinstance',
            name='playerinstance_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Player'),
        ),
    ]
