# Generated by Django 3.0 on 2019-12-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(max_length=500)),
                ('tiny_text', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
