# Generated by Django 2.2.7 on 2019-12-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl_app', '0002_remove_longurl_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='longurl',
            name='IPs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
