# Generated by Django 2.2.7 on 2019-12-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl_app', '0005_longurl_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longurl',
            name='url_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
