# Generated by Django 3.0 on 2019-12-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitter',
            options={'ordering': ['-created']},
        ),
    ]
