# Generated by Django 3.0 on 2019-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_twitter_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='my_image',
            field=models.ImageField(default='avatar/null.jpg', upload_to='avatar/'),
        ),
    ]
