# Generated by Django 3.0 on 2019-12-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0002_auto_20191206_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='abbreviation',
            name='short_url',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
