# Generated by Django 3.0 on 2019-12-04 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 22, 5, 29, 271774, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
