# Generated by Django 3.0 on 2019-12-04 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_auto_20191204_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
