# Generated by Django 3.0 on 2019-12-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
