# Generated by Django 2.2.7 on 2019-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
