# Generated by Django 2.2.7 on 2019-12-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barker_app', '0002_auto_20191211_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bark',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bark',
            name='netlikes',
            field=models.IntegerField(default=0),
        ),
    ]
