# Generated by Django 2.2.7 on 2019-12-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barker_app', '0003_auto_20191213_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bark',
            name='netlikes',
        ),
    ]
