# Generated by Django 2.2.7 on 2019-12-13 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barker_app', '0004_remove_bark_netlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bark',
            name='dislike',
        ),
        migrations.AddField(
            model_name='bark',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bark',
            name='likes',
        ),
        migrations.AddField(
            model_name='bark',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
