# Generated by Django 3.0 on 2019-12-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_app', '0004_shorturl_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='location',
            new_name='remote_addr',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='person',
            new_name='server_name',
        ),
    ]
